- id: '1675285197302'
  alias: USFL planfond cuisine
  description: update the switch state from the light state
  trigger:
  - platform: state
    entity_id: light.planfond
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: light.planfond
    from: 'off'
    to: 'on'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.planfond
        state: 'on'
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.switch_cuisine
    - conditions:
      - condition: state
        entity_id: light.planfond
        state: 'off'
      sequence:
      - service: switch.turn_off
        entity_id: switch.switch_cuisine
- id: '1675285684637'
  alias: ULFS planfond cuisine
  description: update light from switch
  trigger:
  - platform: state
    entity_id:
    - switch.switch_cuisine
    from: 'on'
    to: 'off'
  - platform: state
    entity_id:
    - switch.switch_cuisine
    from: 'off'
    to: 'on'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: switch.switch_cuisine
        state: 'on'
      sequence:
      - service: light.turn_on
        entity_id: light.planfond
    - conditions:
      - condition: state
        entity_id: switch.switch_cuisine
        state: 'off'
      sequence:
      - service: light.turn_off
        entity_id: light.planfond
  mode: single
