- id: '1675562154316'
  alias: update switch state
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.planfond
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - light.planfond
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: light.planfond
          state: 'on'
        - condition: state
          entity_id: switch.switch_planfond
          state: 'off'
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.switch_planfond
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: light.planfond
          state: 'off'
        - condition: state
          entity_id: switch.switch_planfond
          state: 'on'
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.switch_planfond
  mode: single
