binary_sensor:

  - platform: homeassistant
    entity_id: light.planfond
    id: cuisine_planfond_state
    on_state:
      then:
        lambda: |-
          id(text_bright)->execute();

########################### Navigation ############################################

  - platform: nextion
    page_id: 0
    component_id: 1
    id: page0back
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(page_back)->execute(id(current_page_int));
        - logger.log: 
            level: INFO
            format: "page %i, %s"
            args: [id(current_page_int), id(page).c_str()]

  - platform: nextion
    page_id: 0
    component_id: 2
    id: page0next
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(page_next)->execute(id(current_page_int));
        - logger.log: 
            level: INFO
            format: "page %i, %s"
            args: [id(current_page_int), id(page).c_str()]
    
  - platform: nextion
    page_id: 1
    component_id: 10
    id: page1back
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(page_back)->execute(id(current_page_int));
        - logger.log: 
            level: INFO
            format: "page %i, %s"
            args: [id(current_page_int), id(page).c_str()]

  - platform: nextion
    page_id: 1
    component_id: 9
    id: page1next
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(page_next)->execute(id(current_page_int));
        - logger.log: 
            level: INFO
            format: "page %i, %s"
            args: [id(current_page_int), id(page).c_str()]

  - platform: nextion
    page_id: 1
    component_id: 11
    id: page1home
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(cuisinenx).send_command_printf("page home");
            id(current_page_int) = 0;
            id(update_all)->execute();

  - platform: nextion
    page_id: 2
    component_id: 1
    id: page2back
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(page_back)->execute(id(current_page_int));
        - logger.log: 
            level: INFO
            format: "page %i, %s"
            args: [id(current_page_int), id(page).c_str()]

  - platform: nextion
    page_id: 2
    component_id: 2
    id: page2next
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(page_next)->execute(id(current_page_int));
        - logger.log: 
            level: INFO
            format: "page %i, %s"
            args: [id(current_page_int), id(page).c_str()]

  - platform: nextion
    page_id: 2
    component_id: 3
    id: page2home
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(cuisinenx).send_command_printf("page home");
            id(current_page_int) = 0;
            id(update_all)->execute();

  - platform: nextion
    page_id: 3
    component_id: 5
    id: page3back
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(page_back)->execute(id(current_page_int));
        - logger.log: 
            level: INFO
            format: "page %i, %s"
            args: [id(current_page_int), id(page).c_str()]

  - platform: nextion
    page_id: 3
    component_id: 6
    id: page3next
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(page_next)->execute(id(current_page_int));
        - logger.log: 
            level: INFO
            format: "page %i, %s"
            args: [id(current_page_int), id(page).c_str()]#

  - platform: nextion
    page_id: 3
    component_id: 7
    id: page3home
    update_interval: 1s
    on_press:
      then:
        - lambda: |-
            id(cuisinenx).send_command_printf("page home");
            id(current_page_int) = 0;
            id(update_all)->execute();
    
#############################################################################

######################## bouton planfond ####################################

  - platform: nextion
    page_id: 0
    component_id: 4
    component_name: home.b0
    id: home_b0
    on_click:
      then:
        - lambda: |-
            id(planfond_state) = !id(planfond_state);
            id(update_planfond_state_from_home)->execute();
        - logger.log: 
            level: INFO
            format: "planfond_state %i"
            args: [id(planfond_state)]
  
  - platform: nextion
    page_id: 1
    component_id: 12
    component_name: planfond.b0
    id: planfond_b0
    update_interval: 1s
    on_click:
      then:
        - lambda: |-
            id(planfond_state) = !id(planfond_state);
            id(update_planfond_state)->execute();
        - logger.log: 
            level: INFO
            format: "planfond_state %i"
            args: [id(planfond_state)]

#############################################################################

########################### Dim planfond ####################################

  - platform: nextion
    page_id: 1
    component_id: 2
    id: bright_minus
    on_click:
    #possible de deplacer ca dans un script?
      if:
        condition:
          lambda: |-
            return id(cuisine_planfond_state).state;
        then:
          - if:
              condition:
                lambda: 'return stoi(id(bright_text).state) > 13;'
              then:
                homeassistant.service:
                  service: light.turn_on
                  data:
                    entity_id: light.planfond
                    brightness_step: "-13" 
                    transition: "2"


  - platform: nextion
    page_id: 1
    component_id: 3
    id: bright_plus
    on_click:
    #possible de deplacer ca dans un script?
      if:
        condition:
          lambda: |-
            return id(cuisine_planfond_state).state;
        then:
          - if:
              condition:
                lambda: 'return stoi(id(bright_text).state) > 255;'
              then:
                homeassistant.service:
                  service: light.turn_on
                  data:
                    entity_id: light.planfond
                    brightness: "255"
              else:
                homeassistant.service:
                  service: light.turn_on
                  data:
                    entity_id: light.planfond
                    brightness_step: "+13" 
                    transition: "2"

#############################################################################

########################### preset dim button ################################

  - platform: nextion
    page_id: 1
    component_id: 5
    id: bright_25
    on_press:
      then:
        if:
          condition:
            lambda: |-
              return true;
          then:
            homeassistant.service:
              service: light.turn_on
              data:
                entity_id: light.planfond
                brightness: "64"
  
  - platform: nextion
    page_id: 1
    component_id: 6
    id: bright_50
    on_press:
      then:
        if:
          condition:
            lambda: |-
              return true;
          then:
            homeassistant.service:
              service: light.turn_on
              data:
                entity_id: light.planfond
                brightness: "128"

  - platform: nextion
    page_id: 1
    component_id: 7
    id: bright_75
    on_press:
      then:
        if:
          condition:
            lambda: |-
              return true;
          then:
            homeassistant.service:
              service: light.turn_on
              data:
                entity_id: light.planfond
                brightness: "192"
  
  - platform: nextion
    page_id: 1
    component_id: 8
    id: bright_100
    on_click:
      then:
        if:
          condition:
            lambda: |-
              return true;
          then:
            homeassistant.service:
              service: light.turn_on
              data:
                entity_id: light.planfond
                brightness: "255"

#############################################################################

  - platform: nextion
    page_id: 1
    component_id: 7
    component_name: page1.r0
    id: bar_minuterie
    update_interval: 1s
    on_press:
      then:
        logger.log: "bar minuterie"
  
  - platform: nextion
    page_id: 1
    component_id: 7
    component_name: page1.r1
    id: bar_on_off
    update_interval: 1s
    on_press:
      then:
        logger.log: "bar on_off"

  - platform: nextion
    page_id: 1
    component_id: 5
    component_name: page1.bt1
    id: bar_light
    update_interval: 1s

  

  

  
    
